import { z } from 'zod';

/**
 * Void supports two lookup modes:
 *   - by transactionId (preferred — globally unique, generated by us)
 *   - by (terminalId, nsu) for cases where the POS does not retain the transactionId
 */
export const voidTransactionSchema = z
  .object({
    transactionId: z.string().length(26).optional(),
    terminalId: z.string().min(1).max(50).optional(),
    nsu: z.string().min(1).max(50).optional(),
  })
  .refine(
    (v) =>
      !!v.transactionId || (!!v.terminalId && !!v.nsu),
    {
      message: 'Provide transactionId, or both terminalId and nsu',
      path: ['transactionId'],
    },
  );

export type VoidTransactionDto = z.infer<typeof voidTransactionSchema>;
